version: '3'
services:
  mysql:
    container_name: burger-database
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: burger-database
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always